### ISSUE TITLE
[question] rootModule only

### ISSUE THREAD

**Issue by pantonis** [ngx-config/http-loader#3]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => check the README and search github for a similar issue or PR before submitting
[X ] support request => check the README and search github for a similar issue or PR before submitting
[ ] feature request
```

Can this library be used in any other modules or it has to be used only in RootModule?

**Comment by fulls1z3** [comment]
@pantonis have a look at [ng-seed/universal](https://github.com/ng-seed/universal), which covers the basic use case to use this module.
